### ISSUE TITLE
Config option to show article summary on home page

### ISSUE THREAD

**Issue by textbook** [textbook/bulrush#13]
Per #11 an option could be added to show only the summary of the latest article, rather than the full article itself, on the homepage.

**Comment by textbook** [comment]
`index.html` could be switched to something like:

```html
<div class="section">
  {% if HOME_SUMMARY_ONLY %}
    {{  article.summary }}
    <a href="{{ SITEURL }}/{{ article.url }}">Read more...</a>
  {% else %}
    {{ article.content }}
  {% endif %}
  {% include 'comments.html' %}
</div>
```

which would result in:

<img width="959" alt="homesummaryonly" src="https://cloud.githubusercontent.com/assets/785939/25793942/b44e4f2a-33c6-11e7-932f-e69c89e504ce.png">

Would anyone find that useful?

**Comment by r-richmond** [comment]
>  but I tried a quick implementation this morning and don't think it looks that great. Is it something you're still interested in seeing given you've figured out the Disqus part?

Perhaps increasing the length of the summary would improve its look?

But as suggested my interest in this feature has diminished since disqus/your theme shows the comment count on the homepage.

**Comment by philshem** [comment]
I'd be interested in this feature (and don't use Disqus).

**Comment by philshem** [comment]
this has been done in this fork: https://github.com/amitness/bulrush

specifically: https://github.com/amitness/bulrush/blob/master/bulrush/templates/index.html

any chance you can merge it back in?

**Comment by philshem** [comment]
https://github.com/textbook/bulrush/pull/26
