### ISSUE TITLE
JINJA_FILTERS FilterError

### ISSUE THREAD

**Issue by zmcddn** [textbook/bulrush#19]
I have the theme set up followed the steps in Readme file, but when I use the command `pelican content` I have the following error:
`CRITICAL: FilterError: ExternalTool: subprocess returned a non-success result code: 1, stdout=b'', stderr=b"'java' is not recognized as an internal or external command,\r\noperable program or batch file.\r\n"`

My node.js version is `v8.11.4`
Python == 3.7.0
bulrush==0.2.1
pelican==3.7.1
webassets==0.12.1

I also tried run `bulrush.FILTERS` under my python environment and I got the following result:
`{'images': <function extract_images at 0x00000178C165A598>, 'license': <function generate_license at 0x00000178C16BC6A8>, 'schema': <function generate_jsonld_schema at 0x00000178C16BC730>}`

Please help! Thanks a lot!

**Comment by textbook** [comment]
Did you read what it says? `'java' is not recognized as an internal or external command,\r\noperable program or batch file.` - you don't have Java installed. I think this is required for the CSS minifier from `webassets`; it's not needed by the Bulrush-specific filters in `FILTERS`.

**Comment by zmcddn** [comment]
I did read what it says and that's exactly where my confusion comes from, never thought I would need java for this.

I have java installed and it worked fine. Maybe you can update the ReadMe file to include the requirement of java.

Thanks for your help.
