### ISSUE TITLE
request to bulma.io is leaving a cookie

### ISSUE THREAD

**Issue by philshem** [textbook/bulrush#20]
The request to bulma.io for this image:

<img width="340" alt="image" src="https://user-images.githubusercontent.com/4997607/55032474-37a90280-5011-11e9-892a-ef9517580be7.png">

Is leaving the cookie "cfduid" on the browser of website visitors:

<img width="775" alt="image" src="https://user-images.githubusercontent.com/4997607/55032360-fb75a200-5010-11e9-98ad-485d2c148b18.png">

This cookie is from CloudFlare and is [not for tracking](https://support.cloudflare.com/hc/en-us/articles/360024915491), and is for determining unique users with a common IP. It's been discussed [here](https://github.com/mozilla/http-observatory/issues/202).

Is it possible to host the image locally? Or to use only text "Made with Bulma" with a link? Or to point to an image hosted on a site that doesn't leave a cookie?

**Comment by philshem** [comment]
pull request: https://github.com/textbook/bulrush/pull/21

**Comment by textbook** [comment]
Closed by #21
