### ISSUE TITLE
Rendering issue when Embedding jupyter notebook or html scripts

### ISSUE THREAD

**Issue by ayushkumarshah** [textbook/bulrush#29]
I have been enjoying this theme for quite a time until I tried to embed a Jupyter notebook or a Python trinket. Only a small portion of the notebook or code is rendered and the rest is cut. I tried to solve this but have no luck yet. I tried in other themes and it works perfectly but I don't want to switch to another theme again. Can anyone solve this issue?

**Comment by textbook** [comment]
I'm sorry you're having trouble, thanks for letting me know. There's not a lot to go on there, though; could you give a concrete example of something that causes the problem?

**Comment by ayushkumarshah** [comment]
Sure. Here are a few examples:
- Example 1: Embedding Python trinkets into the markdown articles by adding 
```html
<iframe src="https://trinket.io/embed/python/ae8b78e83a" width="100%" height="100%" frameborder="0" marginwidth="0" marginheight="0" allowfullscreen></iframe>
```
results into most of the code cut as shown here.
![image](https://user-images.githubusercontent.com/25257703/82745840-774fb380-9da8-11ea-9901-0f14286dd7fa.png)

While in other themes, it works as required as seen below.
![image](https://user-images.githubusercontent.com/25257703/82745864-ef1dde00-9da8-11ea-84cd-da982d3a05af.png)

- Example 2: Embedding jupyter notebook using pelican-jupyter plugin
When I try to embed jupyter notebooks as content, it has similar problems as seen below:
![image](https://user-images.githubusercontent.com/25257703/82745958-f8f41100-9da9-11ea-8918-281938269942.png)

While the desired output is something like this:
![image](https://user-images.githubusercontent.com/25257703/82745975-293baf80-9daa-11ea-954e-393df5805f61.png)

**Comment by ayushkumarshah** [comment]
![image](https://user-images.githubusercontent.com/25257703/82759470-68e7b300-9e0d-11ea-8982-356d743f83d0.png)

You can see even youtube videos cannot be embedded properly using pelican plugins liquid_tags.youtube

**Comment by textbook** [comment]
It seems like this is an issue with embedding iframes in flexbox - given that Bulrush is based on Bulma, which uses flexbox for the layout, it's out of scope to deal with this at the theme level. You can look at e.g. https://stackoverflow.com/q/33270525/3001761 for fixes.
