### ISSUE TITLE
Formatting for headings and lists in pages?

### ISSUE THREAD

**Issue by sanjayankur31** [textbook/bulrush#31]
Hiya,

Thanks for a great theme! I was setting up our web-space and on the pages, the various sections and lists don't seem to be formatted correctly as they are in articles:

https://ocns.github.io/SoftwareWG/pages/about.html

We're using version `bulrush==0.4.0` here. Is this a known issue perhaps? 

Cheers,

**Comment by textbook** [comment]
Yep, that looks like a bug; thanks for spotting it! The styles for headings of various kinds are scoped to `article .section`:

https://github.com/textbook/bulrush/blob/8ecc9c2e119f42d80df3e13bb40737b0912c1ec1/bulrush/static/css/main.less#L8-L30

but the `pages.html` template doesn't contain an `article` element:

https://github.com/textbook/bulrush/blob/8ecc9c2e119f42d80df3e13bb40737b0912c1ec1/bulrush/templates/page.html#L8-L16

**Comment by sanjayankur31** [comment]
Ah! That makes sense! Please do let me know if I can help with the fix in any way.
