### ISSUE TITLE
In Pelican 3.7, JINJA_EXTENSIONS has been replaced with JINJA_ENVIRONMENT

### ISSUE THREAD

**Issue by jerryasher** [textbook/bulrush#6]
Following the release notes https://blog.getpelican.com/pelican-3.7-released.html

> JINJA_EXTENSIONS has been replaced by the JINJA_ENVIRONMENT setting. Any plugins that refer to the former setting will need to be updated. Refer to the corresponding entry in the Settings documentation for more information.

I think this works

```
JINJA_ENVIRONMENT = {
    'extensions': ['webassets.ext.jinja2.AssetsExtension', 'jinja2.ext.with_']
}
```

**Comment by textbook** [comment]
Indeed that's what I [currently have][1]; forgot to update the `README` for that, thanks for the reminder.

  [1]: https://github.com/textbook/textbook.github.io-source/blob/3ba33319e39b5f041bb43310b87d6cb1b2e7f8b4/pelicanconf.py#L18
